### ISSUE TITLE
Image should be removed before another popup present.

### ISSUE THREAD

**Issue by alicanbatur** [bfeher/BFRadialWaveHUD#5]
Hi,

First, thanks. Nice lib.

Here is my scenerio;

I create one instance of BFRadialWaveHUD. And I use this instance anywhere. 
first show a success message. then tap to dismiss.
and then show error message with that same instance. You will see the problem. Error X will place over success tick. 

Any advice.

**Comment by bfeher** [comment]
Hi @alicanbatur ! 
Nice find, thanks! I'll let you know when the fix is posted.

![ios simulator screen shot may 29 2015 9 17 01 am](https://cloud.githubusercontent.com/assets/3466708/7873951/d699c040-05e3-11e5-9d09-fcba1ff990b5.png)

**Comment by bfeher** [comment]
This is actually a bug in [BFRadialWaveView](https://github.com/bfeher/BFRadialWaveView) so I will open [this issue](https://github.com/bfeher/BFRadialWaveView/issues/3) over there too.

**Comment by bfeher** [comment]
I fixed the [bug](https://github.com/bfeher/BFRadialWaveView/issues/3) with [BFRadialWaveView](https://github.com/bfeher/BFRadialWaveView).

I've also just released a new version, [1.5.3](https://github.com/bfeher/BFRadialWaveHUD/commit/69dfd9368b9a5e5f341556bb288567c91defcc6b) which fixes a [different bug](https://github.com/bfeher/BFRadialWaveHUD/issues/6) and also includes the latest version of BFRadialWaveView so I recommend installing the latest version of BFRadialWaveHUD :)

If you don't want to install the latest version of the HUD, you can get the fix from BFRadialWaveView by running this command:

```
pod install
```

since BFRadialWaveHUD's podfile points at :HEAD of BFRadialWaveView.

Thanks again :D

**Comment by alicanbatur** [comment]
Yess! 

You fixed. Thank you.
